version: 2.1

orbs:
  docker: circleci/docker@3.0.0

# Job definitions
jobs:
  build:
    executor: docker/docker
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-libssh2-build-{{ .Branch }}
            - v1-libssh2-build-
      - run:
          name: Set up Docker Buildx context
          command: docker buildx create --name libssh2-builder --use
      - docker/build:
          image: verdigristech/libssh2-wasm
          use_buildkit: true
          extra_build_args:
            --progress=plain
            --cache-from=local,src=/tmp/buildx-cache
            --cache-to=type=local,mode=max,dest=/tmp/buildx-cache
            --output=type=tar,dest=libssh2.tar
      - run:
          name: Extract the build output
          command: |
            mkdir -p dist
            tar -xf libssh2.tar -C dist
      - save_cache:
          paths:
            - /tmp/buildx-cache
          key: v1-libssh2-build-{{ .Branch }}
      - persist_to_workspace:
          root: dist
          paths:
            - dist/libssh2.js
            - dist/libssh2.wasm
      - store_artifacts:
          path: dist

# Workflows
workflows:
  release:
    jobs:
      - build
